version: '3'


services:
  potato-consumer:
    build:
      .
    container_name: potato-consumer
    depends_on:
      - potatoes-queue
    environment:
      SPRING_RABBITMQ_HOST: potatoes-queue


  potatoes-queue:
    container_name: "potatoes-queue"
    build:
      context: ./rabbitMqConfig/
      dockerfile: ./Dockerfile
    volumes:
      - potatoes-queue-data:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  #
  # Volumes
  #
volumes:
  potatoes-queue-data:
    driver: "local"
