version: '3'


services:
  berlin-news:
    build:
      .
    container_name: berlin-news
    depends_on:
      - news-queue
    environment:
      SPRING_RABBITMQ_HOST: news-queue
      AREA_REGION_NAME: berlin
      AREA_COUNTRY_NAME: germany

  veneto-news:
    build:
      .
    container_name: veneto-news
    depends_on:
      - news-queue
    environment:
      SPRING_RABBITMQ_HOST: news-queue
      AREA_REGION_NAME: veneto
      AREA_COUNTRY_NAME: italy



  news-queue:
    container_name: "news-queue"
    build:
      context: ./rabbitMqConfig/
      dockerfile: ./Dockerfile
    volumes:
      - news-queue-data:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  #
  # Volumes
  #
volumes:
  news-queue-data:
    driver: "local"
