version: '3'


services:

  news-queue:
    container_name: "news-queue"
    build:
      context: ./rabbitMqConfig/
      dockerfile: ./Dockerfile
    volumes:
      - news-queue-data:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  berlin-news:
    build:
      .
    container_name: berlin-news
    restart: always
    depends_on:
      - news-queue
    environment:
      SPRING_RABBITMQ_HOST: news-queue
      REGION_NAME: berlin
      COUNTRY_NAME: germany
      TOPICS: 'news.beer.#,news.corona.#,news.weather.germany.berlin, news.vegetables.potatoes.#'

  veneto-news:
    build:
      .
    container_name: veneto-news
    restart: always
    depends_on:
      - news-queue
    environment:
      SPRING_RABBITMQ_HOST: news-queue
      REGION_NAME: veneto
      COUNTRY_NAME: italy
      TOPICS: 'news.beer.#,#.corona.#,news.weather.italy.veneto, news.vegetables.*.discount'


  #
  # Volumes
  #
volumes:
  news-queue-data:
    driver: "local"
