spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672

area:
  region:
    name: ${region-name}
  country:
    name: ${country-name}

queue-properties:
  topics: ${topics}
  queue_name: news-${country-name}-${region-name}
  exchange_name: news_exchange
